version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  tests:core:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
      - run: gradle integracao-continua-core:test
      - store_test_results:
          path: integracao-continua-core/build/test-results
  tests:providers:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
      - run: gradle integracao-continua-dataprovider:test
      - store_test_results:
          path: integracao-continua-dataprovider/build/test-results
  tests:entrypoints:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
      - run: gradle integracao-continua-entrypoint:test
      - store_test_results:
          path: integracao-continua-entrypoint/build/test-results
  tests:configuration:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
      - run: gradle integracao-continua-configuration:test
      - store_test_results:
          path: integracao-continua-configuration/build/test-results
workflows:
  version: 2
  jobs:
    - build
    - tests:core:
        requires:
          - build
    - tests:providers:
        requires:
          - build
    - tests:entrypoints:
        requires:
          - build
    - tests:configuration:
        requires:
          - build