name: Testing action

on: [pull_request]

jobs:
  ci-smell-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: allanfvc/cisc-action@v1
      with:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
