name: Kotlin Lint

on: push

jobs:
   lint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2
       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"