name: Lint

on:
  pull_request

jobs:
   lint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2
       - name: "lint"
         uses: github/super-linter@v3.15.5
         env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
